### ISSUE TITLE
Work on Ghost v2?

### ISSUE THREAD

**Issue by pascalandy** [shiva-hack/ghost-digitalocean#2]
Hi, 

As there was a breaking change between v1 and v2, I'm wondering if this storage adapter works on Ghost v2. 

Thank you!
P

**Comment by catmangox** [comment]
I have the same question, can this plugin works with  ghost V2?

**Comment by shiva-hack** [comment]
Hello! @pascalandy , @Skyepose !
I checked the plugin on the latest ghost version and looks like it works fine! Here's a screenshot!

![2018-12-27_1543](https://user-images.githubusercontent.com/36563140/50476479-54bc3e00-09ee-11e9-923a-4637a6225a06.png)

**Comment by pascalandy** [comment]
Thanks for confirming!
